apiVersion : apps/v1
kind: Deployment
metadata:
  name: "web" 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web 
    spec:
      containers:
        - name: "web"
          image: "fasthack10.azurecr.io/web:1.0"
          ports:
          - containerPort: 80
          env:
          - name: API_URL
            value: http://10.0.132.90:8080
---
apiVersion: v1
kind: Service
metadata:
    name: "web"
    labels:
        app: "web"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "web"

